name: Deploy 🚀

on: push

jobs:
  uploadToGDriveDev:
    name: Upload to Develop
    if: github.ref == 'refs/heads/Dev'
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-Android
          path: build/Android

      - name: Upload to g-drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "/home/runner/work/EDA/EDA/build/Android/Android.apk"
          folderId: ${{ secrets.FOLDER_ID_DEV }}
          overwrite: "true"
          
  uploadToGDriveQA:
    name: Upload to QA
    if: github.ref == 'refs/heads/QA'
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-Android
          path: build/Android

      - name: Upload to g-drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "/home/runner/work/EDA/EDA/build/Android/Android.apk"
          folderId: ${{ secrets.FOLDER_ID_QA }}
          overwrite: "true"
          
  uploadToGDriveProd:
    name: Upload to Production
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build-Android
          path: build/Android

      - name: Upload to g-drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "/home/runner/work/EDA/EDA/build/Android/Android.apk"
          folderId: ${{ secrets.FOLDER_ID_PROD }}
          overwrite: "true"