name: Test 🧪 feature branch

on:
  push:
    branches-ignore:
      - master
      - QA
      - Dev

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  callTo-Labeler:
    uses: VoroninLevan/EDA/.github/workflows/Labeler.yml
  callTo-TestWF:
    uses: VoroninLevan/EDA/.github/workflows/TestWF.yml