name: Test 🧪 Scan 🔍 Build 🔨 Deploy 🚀 QA

on:
  pull_request:
    branches:
      - master
        
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  callTo-Labeler:
    uses: VoroninLevan/EDA/.github/workflows/Labeler.yml@master
    permissions:
      contents: read
      pull-requests: write
  callTo-Scan:
    uses: VoroninLevan/EDA/.github/workflows/SonarScan.yml@master
    secrets: inherit
  callTo-TestWF:
    needs: callTo-Scan
    uses: VoroninLevan/EDA/.github/workflows/TestWF.yml@master
    secrets: inherit
  callTo-BuildAndroidPROD:
    needs: callTo-TestWF
    uses: VoroninLevan/EDA/.github/workflows/BuildAndroidProd.yml@master
    secrets: inherit